### ISSUE TITLE
conf_unfolder not working with list and grid params together.

### ISSUE THREAD

**Issue by L1nusB** [ALRhub/cw2#66]
Hi, 
the last commit that added the debug convenience features, I ran into an issue when trying to use both list and grid parameters in the configuration yaml that worked before. 
After some digging I found that the issue seems to be caused during `expand_experiments` in `conf_unfolder.py` where the expansion of the experiment_configs in line 65-66 is conditioned on whether debug is True or False but the list splicing returns an empty list if debug is set to False as conditioning in the indicing process does not seem to work as the author expected (at least on my system):
```
experiment_configs += params_combine(
                config, key, iter_func)[:1 if debug else 0:]
```
I resolved this issue locally by doing it the same way it is done in the other cases by factoring it out and conditioning later:
```
expansion = params_combine(config, key, iter_func)

experiment_configs += expansion[:1] if debug else expansion
```

**Comment by LiXiling** [comment]
Thanks for opening this issue!
Let me make a small fix. Do you have time to try and test it afterwards?

**Comment by LiXiling** [comment]
Could you test the branch `fix/issue66` ?

**Comment by L1nusB** [comment]
I tested the fix on branch `fix/issue66` and it resolved the issue that was occuring for me.
Now all combinations of list/grid work fine again.
Thanks for your fast response.
